# Generated by Django 5.2.12 on 2026-04-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main_page', '0013_remove_user_isadmin_remove_user_isinspector_and_more'),
        ('profiles', '0012_alter_medicalcheck_medic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicalcheck',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='certificationtest',
            name='created_by_admin',
        ),
        migrations.RemoveField(
            model_name='certificationtest',
            name='created_by_inspector',
        ),
        migrations.AddField(
            model_name='certificationtest',
            name='creator_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип создателя'),
        ),
        migrations.AddField(
            model_name='certificationtest',
            name='creator_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID создателя'),
        ),
        migrations.AddField(
            model_name='medicalcheck',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='medicalcheck',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отмены'),
        ),
        migrations.AddField(
            model_name='medicalcheck',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменён'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'Вариант 1'), (2, 'Вариант 2'), (3, 'Вариант 3')], verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=200, verbose_name='Вариант 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=200, verbose_name='Вариант 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=200, verbose_name='Вариант 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sick_leaves', to='main_page.medic', verbose_name='Выдал медработник'),
        ),
        migrations.AlterField(
            model_name='videoinspection',
            name='check_mask',
            field=models.BooleanField(default=True, verbose_name='Проверять маски'),
        ),
    ]
