# Generated by Django 5.2.12 on 2026-04-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_remove_admin_isactive_remove_department_created_at_and_more'),
        ('profiles', '0013_alter_medicalcheck_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationtest',
            name='creator_content_type',
        ),
        migrations.RemoveField(
            model_name='certificationtest',
            name='creator_object_id',
        ),
        migrations.AddField(
            model_name='certificationtest',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to='main_page.admin', verbose_name='Создал (администратор)'),
        ),
        migrations.AddField(
            model_name='workobject',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_objects', to='main_page.admin', verbose_name='Создал (администратор)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to='main_page.admin', verbose_name='Создал (администратор)'),
        ),
    ]
