# Generated by Django 5.2.12 on 2026-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_alter_user_system_role_medic'),
        ('profiles', '0012_alter_medicalcheck_medic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isInspector',
        ),
        migrations.AlterField(
            model_name='medic',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='isInspector',
            field=models.BooleanField(default=False, verbose_name='Инспектор'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_certifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='documents',
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Работает'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_certifications',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='profiles.certificationtest', verbose_name='Назначенные аттестации'),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='certified_users', to='profiles.certificationtest', verbose_name='Пройденные аттестации'),
        ),
        migrations.AddField(
            model_name='user',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='profiles.document', verbose_name='Назначенные документы'),
        ),
    ]
