# Generated by Django 5.2.12 on 2026-04-26 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_remove_user_isadmin_remove_user_isinspector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='isInspector',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='isInspector',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='isInspector',
        ),
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.department', verbose_name='Закрепленный участок'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.department', verbose_name='Закрепленный участок'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.department', verbose_name='Закрепленный участок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Сотрудник'), ('lead', 'Старший сотрудник')], default='worker', max_length=10, verbose_name='Роль в наряде'),
        ),
    ]
