# Generated by Django 5.2.12 on 2026-04-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_remove_admin_isadmin_remove_admin_isinspector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='position',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='position',
            name='is_managerial',
        ),
        migrations.RemoveField(
            model_name='position',
            name='requires_medical_check',
        ),
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.department', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.department', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.department', verbose_name='Участок'),
        ),
    ]
